[tool.poetry]
name = "magika"
version = "0.6.0-dev"
description = "A tool to determine the content type of a file with deep-learning"
authors = ["Yanick Fratantonio <yanickf@google.com>"]
readme = "README.md"
packages = [{include = "magika"}]

[tool.poetry.dependencies]
python = "^3.8,<3.13"
click = "^8.1.3"
tqdm = "^4.66.2"
onnxruntime = "^1.17.0"
numpy = [
    {version = "^1.24", python = ">=3.8,<3.9"},
    {version = "^1.26", python = ">=3.9,<3.13"}
]
tabulate = "^0.9.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
ipython = [
    {version = "^8.12.3", python = ">=3.8,<3.9"},
    {version = "^8.18.1", python = ">=3.9,<3.10"},
    {version = "^8.21.0", python = ">=3.10,<3.13"}
]
ruff = ">=0.2.2,<0.4.0"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "I001"]
ignore = []
