name: pytest
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths: [python]

jobs:
  unittesting:
    strategy:
      matrix:
        python-version: ["3.9.x", "3.10.x", "3.11.x", "3.12.x"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.7.1"
      - name: Install the project dependencies
        run: |
          cd python
          poetry install
      - name: Run the automated tests
        run: |
          cd python
          poetry run pytest tests -m "not slow"
