name: Python - test 1

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "python/**"
      - "rust/**"
      - "tests_data/**"
      - ".github/workflows/python-test-suite.yml"

permissions:
  contents: read

env:
  UV_VERSION: "0.9.22"

jobs:
  unit-testing-two:
    name: unit testing two
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - name: Run magika
        run: uv run magika -V
        working-directory: python
