name: Python - publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      # This permission is required for trusted publishing.
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # pin@v4

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # pin@v5
        with:
          python-version: '3.10.x'

      - name: Install Poetry
        uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b # pin@v1
        with:
          virtualenvs-create: false

      - name: Update version (kept at 0.0.0) in pyproject.toml and build
        run: |
          cd python
          poetry version ${{ github.ref_name }}
          poetry build

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@eef668ab210066f42abfe3f2af4e03ec24f30089 # pin@v1.0.3

      - name: Publish the package with poetry
        run: |
          cd python
          poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
