name: Python - test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'python/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/**'

jobs:
  unit-testing:
    strategy:
      matrix:
        python-version: ["3.8.x", "3.9.x", "3.10.x", "3.11.x", "3.12.x"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.7.1"

      - name: Install the project dependencies
        working-directory: python
        run: poetry install

      - name: Run ruff check
        working-directory: python
        run: poetry run ruff check --verbose

      - name: Run ruff format check
        working-directory: python
        run: poetry run ruff format --check --verbose

      - name: Run mypy
        working-directory: python
        run: poetry run mypy magika tests

      - name: Run pytest
        working-directory: python
        run: poetry run pytest tests -m "not slow"
