name: Website - tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "website/**"
      - "js/**"
      - "tests_data/**"
      - ".github/workflows/website-*"
permissions:
  contents: read
jobs:
  build-and-test:
    strategy:
      matrix:
        node-version: ["20"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install js dependencies
        working-directory: js
        run: yarn install --frozen-lockfile
      - name: Build js
        working-directory: js
        run: yarn run build
      - name: Create magika link
        working-directory: js
        run: yarn link
      - name: Link to local magika
        working-directory: website
        run: yarn link magika
      - name: Install website dependencies
        working-directory: website
        run: yarn install --frozen-lockfile
      - name: Build website
        working-directory: website
        run: yarn build
      # TODO: add some actual testing
